version: "3.7"

services:

  php:
    build:
      context: docker/php
    container_name: ${APP_NAME}-php
    working_dir: /application
    volumes:
      - ../emporio-backend:/application
    links:
      - mysql
    networks:
      - emporio-network

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    working_dir: /application
    volumes:
      - ../emporio-backend:/application
      - ./docker/nginx/${APP_ENV}/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    ports:
      - '80:80'
    depends_on:
      - php
    networks:
      - emporio-network

  mysql:
    image: mysql:8.0.25
    container_name: ${APP_NAME}-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: emporio
      MYSQL_ROOT_PASSWORD: root
    networks:
      - emporio-network

  frontend:
    container_name: ${APP_NAME}-frontend
    build:
      context: docker/vue
      dockerfile: Dockerfile
    volumes:
      - ../emporio:/app
      - /app/node_modules
    ports:
      - '2020:2020'
    networks:
      - emporio-network

networks:
  emporio-network:
    driver: bridge
    name: ${APP_NAME}-network
